# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitol.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kayitoll(object):
    def setupUi(self, kayitoll):
        kayitoll.setObjectName("kayitoll")
        kayitoll.resize(387, 561)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dht11_700p.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        kayitoll.setWindowIcon(icon)
        kayitoll.setStyleSheet("QLabel{\n"
"font: 9pt \"Impact\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(kayitoll)
        self.centralwidget.setObjectName("centralwidget")
        self.kayitol = QtWidgets.QPushButton(self.centralwidget)
        self.kayitol.setGeometry(QtCore.QRect(20, 390, 341, 61))
        self.kayitol.setObjectName("kayitol")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 341, 351))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 301, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.adsoyad = QtWidgets.QLineEdit(self.layoutWidget)
        self.adsoyad.setDragEnabled(False)
        self.adsoyad.setClearButtonEnabled(True)
        self.adsoyad.setObjectName("adsoyad")
        self.verticalLayout_2.addWidget(self.adsoyad)
        self.kullaniciadi = QtWidgets.QLineEdit(self.layoutWidget)
        self.kullaniciadi.setClearButtonEnabled(True)
        self.kullaniciadi.setObjectName("kullaniciadi")
        self.verticalLayout_2.addWidget(self.kullaniciadi)
        self.sifre = QtWidgets.QLineEdit(self.layoutWidget)
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre.setClearButtonEnabled(True)
        self.sifre.setObjectName("sifre")
        self.verticalLayout_2.addWidget(self.sifre)
        self.sifretekrar = QtWidgets.QLineEdit(self.layoutWidget)
        self.sifretekrar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifretekrar.setClearButtonEnabled(True)
        self.sifretekrar.setObjectName("sifretekrar")
        self.verticalLayout_2.addWidget(self.sifretekrar)
        self.email = QtWidgets.QLineEdit(self.layoutWidget)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.verticalLayout_2.addWidget(self.email)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.giris = QtWidgets.QPushButton(self.centralwidget)
        self.giris.setGeometry(QtCore.QRect(20, 460, 341, 31))
        self.giris.setObjectName("giris")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        kayitoll.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(kayitoll)
        self.statusbar.setObjectName("statusbar")
        kayitoll.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(kayitoll)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 387, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuProgram = QtWidgets.QMenu(self.menuBar)
        self.menuProgram.setObjectName("menuProgram")
        kayitoll.setMenuBar(self.menuBar)
        self.actionKay_t_Ol = QtWidgets.QAction(kayitoll)
        self.actionKay_t_Ol.setObjectName("actionKay_t_Ol")
        self.actionGiri = QtWidgets.QAction(kayitoll)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHakk_nda = QtWidgets.QAction(kayitoll)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.actionGiri_2 = QtWidgets.QAction(kayitoll)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.actionKay_t_Ol_2 = QtWidgets.QAction(kayitoll)
        self.actionKay_t_Ol_2.setObjectName("actionKay_t_Ol_2")
        self.actionHakk_nda_2 = QtWidgets.QAction(kayitoll)
        self.actionHakk_nda_2.setObjectName("actionHakk_nda_2")
        self.action_cikisk = QtWidgets.QAction(kayitoll)
        self.action_cikisk.setObjectName("action_cikisk")
        self.menuProgram.addAction(self.actionGiri_2)
        self.menuProgram.addAction(self.actionHakk_nda_2)
        self.menuProgram.addAction(self.action_cikisk)
        self.menuBar.addAction(self.menuProgram.menuAction())

        self.retranslateUi(kayitoll)
        QtCore.QMetaObject.connectSlotsByName(kayitoll)

    def retranslateUi(self, kayitoll):
        _translate = QtCore.QCoreApplication.translate
        kayitoll.setWindowTitle(_translate("kayitoll", "Kayıt Ol"))
        self.kayitol.setText(_translate("kayitoll", "Kayıt Ol"))
        self.groupBox.setTitle(_translate("kayitoll", "Kayıt Ol"))
        self.label.setText(_translate("kayitoll", "Ad - Soyad*"))
        self.label_2.setText(_translate("kayitoll", "Kullanıcı Adı*"))
        self.label_3.setText(_translate("kayitoll", "Şifre*"))
        self.label_4.setText(_translate("kayitoll", "Şifre Tekrar*"))
        self.label_5.setText(_translate("kayitoll", "E-Mail"))
        self.giris.setText(_translate("kayitoll", "Zaten Üyeyim"))
        self.menuProgram.setTitle(_translate("kayitoll", "Program"))
        self.actionKay_t_Ol.setText(_translate("kayitoll", "Kayıt Ol"))
        self.actionGiri.setText(_translate("kayitoll", "Giriş"))
        self.actionHakk_nda.setText(_translate("kayitoll", "Hakkında"))
        self.actionGiri_2.setText(_translate("kayitoll", "Giriş"))
        self.actionKay_t_Ol_2.setText(_translate("kayitoll", "Kayıt Ol"))
        self.actionHakk_nda_2.setText(_translate("kayitoll", "Hakkında"))
        self.action_cikisk.setText(_translate("kayitoll", "Çıkış"))

